apiVersion: v1
kind: Service
metadata:
  name: {{ template "demo-healthcheck.fullname" . }}
  labels:
{{ include "demo-healthcheck.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "demo-healthcheck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
