apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: app-dev
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: app-dev
spec:
  resources:
    requests:
      storage: 200m
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: app-dev
  labels:
    app: mongodb
spec:
  containers:
    - image: hub.iflytek.com/zlyy-public/mongo
      name: mongodb
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      ports:
        - containerPort: 27017
          protocol: TCP
      env:
        - name: TZ
          value: Asia/Shanghai
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: mongodb-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: app-dev
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30017
      port: 27017
      targetPort: 27017
