apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: infrastructure
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 5601
  selector:
    app: kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: infrastructure
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: hub.iflytek.com/zlyy-public/kibana:6.4.3
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 300Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: discovery.type
              value: "single-node"
            - name: XPACK_MONITORING_ENABLED
              value: "true"
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
